# Generated by Django 6.0.4 on 2026-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('editor', 'Editor')], max_length=10),
        ),
    ]
