# Generated by Django 6.0.4 on 2026-04-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='invited_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='app.appuser'),
        ),
        migrations.AddField(
            model_name='project',
            name='raw_video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('editing', 'Editing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
