# Generated by Django 6.0.4 on 2026-04-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_videoversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='invited_editor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='raw_video',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.DeleteModel(
            name='VideoVersion',
        ),
    ]
