# Generated by Django 6.0.4 on 2026-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='timestamp_sec',
            field=models.FloatField(help_text='Video time in seconds'),
        ),
    ]
